
# Enabling H2 Console
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  profiles:
    active:


rs.pscode.firebase.database.url: https://budget-tool-311f2.firebaseio.com
rs.pscode.firebase.config.path: budget-tool-311f2-firebase-adminsdk-i7d8m-3f908daf73.json

#rs.pscode.firebase.enabled: true/false

