
# Enabling H2 Console
spring:
  datasource:
    url: ## override
#    driverClassName: com.mysql.jdbc.Driver
    username: ## override
    password: ## override
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.naming_strategy: org.hibernate.cfg.DefaultNamingStrategy

  h2.console.enabled: false
  profiles:
    active:

rs.pscode.firebase.database.url: https://budget-tool-311f2.firebaseio.com
rs.pscode.firebase.config.path: budget-tool-311f2-firebase-adminsdk-i7d8m-3f908daf73.json

#rs.pscode.firebase.enabled: true/false


hibernate:

  show_sql: true
  format_sql: true

