
# Enabling H2 Console
spring:
  datasource:
    url: jdbc:mysql://database-1.ces2s868gz3k.ap-southeast-2.rds.amazonaws.com:3306/MainDB
    #    driverClassName: com.mysql.jdbc.Driver
    username: admin
    password: 'wbO3K6CBPpLrp!RCBQA3k%#mosV#6'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.naming_strategy: org.hibernate.cfg.DefaultNamingStrategy

#  h2.console.enabled: false
  profiles:
    active: local

rs.pscode.firebase.database.url: https://budget-tool-311f2.firebaseio.com
rs.pscode.firebase.config.path: budget-tool-311f2-firebase-adminsdk-i7d8m-5138be61f4.json

#rs.pscode.firebase.enabled: true/false
#server.port: 5000

hibernate:

  show_sql: true
  format_sql: true

